import React from 'react';
import { X, Printer, Share2, FileCheck } from 'lucide-react';
import './ReportModal.css';

const ReportModal = ({ data = {}, onClose }) => {
  const questions = data.questions || [];
  const answers = data.answers || [];

  return (
    <div className="modal-overlay">
      <div className="modal-content report-modal">
        <div className="modal-header no-print">
          <h2 className="modal-title">Exam Review Report</h2>
          <div className="modal-actions">
            <button className="btn-secondary" onClick={() => window.print()}>
              <Printer size={16} /> Print
            </button>
            <button className="btn-secondary" onClick={() => alert('Report link copied to clipboard!')}>
              <Share2 size={16} /> Share
            </button>
            <button className="btn-icon" onClick={onClose}>
              <X size={20} />
            </button>
          </div>
        </div>
        
        <div className="printable-report">
          <div className="report-header">
            <div className="report-branding">
              <div className="logo-icon-small">V</div>
              <h2>VedaAI</h2>
            </div>
            <div className="report-meta">
              <p><strong>Student:</strong> {data.studentName || 'Student Submission'}</p>
              <p><strong>Class:</strong> {data.className || 'Exam Review'}</p>
              <p><strong>Date:</strong> {data.date || new Date().toLocaleDateString()}</p>
            </div>
          </div>
          
          <div className="report-score-banner">
            <div className="score-summary">
              <span className="label">Final Score</span>
              <div className="score-digits">
                <span className="earned">{data.score || 0}</span>
                <span className="total">/{data.maxScore || 0}</span>
              </div>
            </div>
            <div className="grade-stamp">
              <FileCheck size={32} color="#1e7e34" />
              <span>Graded</span>
            </div>
          </div>
          
          <div className="report-details">
            <h3>Question Breakdown</h3>
            <table className="breakdown-table">
              <thead>
                <tr>
                  <th>Q#</th>
                  <th>Question</th>
                  <th>Status</th>
                  <th>Marks</th>
                  <th>AI Feedback</th>
                </tr>
              </thead>
              <tbody>
                {questions.map(q => {
                  const ans = answers.find(a => String(a.qId).toLowerCase() === String(q.id).toLowerCase());
                  return (
                    <tr key={q.id}>
                      <td>Q{q.id}</td>
                      <td>{q.text}</td>
                      <td>
                        {ans ? (ans.isCorrect ? '✅ Correct' : '❌ Incorrect') : '⚠️ Unanswered'}
                      </td>
                      <td>{ans ? ans.marksGiven : 0} / {q.marks}</td>
                      <td className="feedback-cell">
                        {ans ? (ans.text ? `"${ans.text}" — ` : '') + (ans.feedback || (ans.isCorrect ? 'Matches expected solution.' : 'Review calculation.')) : 'No answer sheet matching found.'}
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
          
          <div className="report-footer">
            <p>Generated by VedaAI Teacher Toolkit</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportModal;
